# Generated by Django 5.2.5 on 2026-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0002_comment_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar_url",
            field=models.TextField(blank=True),
        ),
    ]
